# Generated by Django 4.2.6 on 2023-11-06 08:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='purchase_datetime',
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
